#!/usr/bin/env python3

import sys
import os
import os.path

# change this if you want a different one
interpreter="python3"

# help section
if len(sys.argv) == 1:
	sys.argv.append("--help")

if (sys.argv[1] in ["--help", "-h", "-help", "help", "getopt", "usage"]):
	sys.stderr.write("""


JLOH, version 0.12.0

--------------------------------------------------------------------------------
by Matteo Schiavinato
largely based on:
Pryszcz et al., 2014    https://doi.org/10.1093/gbe/evu082
Mixao et al., 2019      https://doi.org/10.3389/fgene.2019.00383
--------------------------------------------------------------------------------

Commands:

 -- Extraction
    extract             Extract LOH blocks from VCF, BAM and FASTA files
    filter              Filter extracted LOH blocks
    intersect           Intersect LOH blocks between two runs

 -- Calculations
    density             Estimate heterozygous and homozygous SNP densities

 -- Graphical tools
    plot                Meaningful plots from the the results from "extract"


""")
else:
	args = " ".join(sys.argv[1:])
	PROGRAMDIR = os.path.dirname(os.path.realpath(__file__))
	os.system(f"{interpreter} {PROGRAMDIR}/src/{args}")
